export const CORASSENTOSELECIONADO = "#1AAE9E";
export const CORASSENTODISPONIVEL = "#C3CFD9";
export const CORASSENTOINDISPONIVEL = "#FBE192";
export const BORDAASSENTOSELECIONADO = "#0E7D71";
export const BORDAASSENTODISPONIVEL = "#7B8B99";
export const BORDASSENTOINDISPONIVEL = "#F7C52B";
